### PR TITLE
Do not check for a manually changed issue date when rebasing

### PR DESCRIPTION
**Pull request by sschuberth**

### CODE REVIEW

**Comment by sschuberth** [comment]
@dscho Did you have a chance to test this?

**Comment by dscho** [comment]
@sschuberth Unfortunately not yet :-( Sorry!

**Comment by sschuberth** [comment]
@dscho If you have no time to test this, any objection that I myself or @t-b test this and merge to clean this up?

**Comment by dscho** [comment]
No objections, but I thought we're switching to MSys2?

**Comment by sschuberth** [comment]
Sure, I just want to wrap things up and not have any unresolved PRs.

**Comment by dscho** [comment]
Makes sense!

**Comment by sschuberth** [comment]
Merged manually with some minor changes.

**Pull request closed without merging**
