### PR TITLE
mingw32-curl: Update to version 7.40.0

### PR DESCRIPTION
**Pull request by sschuberth**
Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

**Comment by sschuberth** [comment]
Build job: https://dscho.cloudapp.net/job/sdk-create-packages/45/

**Comment by t-b** [comment]
The changes look good, although the jenkins build did not suceed.

**Comment by sschuberth** [comment]
Looking closer at the failed Jenkins jobs reveals that it failed for bogus reasons:

    Can't exec "curl": No such file or directory at lib/mk-ca-bundle.pl line 122.

And that line has

    my $curl = `curl -V`;

So building cURL depends on cURL ... one more reason besides https://github.com/t-b/mgwport/commit/ff2012015f8ccfcee29b3d526da3531fcc203e0f to require cURL. See https://github.com/git-for-windows/sdk/pull/28.

**Comment by sschuberth** [comment]
Hmm, now https://dscho.cloudapp.net/job/sdk-create-packages/48/ does not have the error in `mk-ca-bundle.pl` anymore, but the build still fails. I'll take a look at this some time next week probably.

**Comment by sschuberth** [comment]
I've fixed the issue, build https://dscho.cloudapp.net/job/sdk-create-packages/56/ is fine now, and the binaries are at Bintray already.

**Pull request merged**
